#
# Copyright (c) 2019 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

trigger:
- master

jobs:
- job: packages
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  # azure docker installation task
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/docker-installer?view=azure-devops 
  - task: DockerInstaller@0
    displayName: 'Install Docker'